export interface ServiceItem {
    slug: string
    title: string
    shortDescription: string
    fullDescription: string[]
    features: string[]
    benefits: string[]
    process: { step: string; description: string }[]
    category: 'family-office' | 'cybersecurity'
    icon: string
}

export const familyOfficeServices: ServiceItem[] = [
    {
        slug: 'accounting',
        title: 'Accounting & Bill Pay',
        shortDescription: 'Comprehensive financial management and payment processing.',
        fullDescription: [
            'Our accounting and bill pay services provide comprehensive financial management tailored to the unique needs of high-net-worth families. We understand that managing complex financial structures requires precision, discretion, and expertise.',
            'We handle all aspects of financial record-keeping, from daily transactions to complex multi-entity structures, ensuring accuracy and compliance with all regulatory requirements. Our team of experienced professionals brings institutional-quality processes to your family office.',
            'Our team manages vendor payments, tracks expenses, and provides detailed reporting to give you complete visibility into your financial position. We work seamlessly with your existing advisors, accountants, and legal counsel to ensure coordinated financial management.',
            'With our secure, technology-enabled platform, you have real-time access to your financial information while maintaining the highest standards of data security and privacy.',
        ],
        features: [
            'Daily transaction processing and reconciliation',
            'Multi-entity and multi-currency accounting',
            'Vendor payment management and approval workflows',
            'Expense tracking and categorization',
            'Bank and investment account reconciliation',
            'Financial statement preparation (monthly, quarterly, annual)',
            'Cash flow management and forecasting',
            'Audit support and documentation',
            'Tax document preparation and coordination',
            '1099 and W-2 processing',
            'Charitable giving tracking',
            'Real estate and property accounting',
        ],
        benefits: [
            'Reduce administrative burden on family members',
            'Ensure accuracy and compliance',
            'Gain real-time visibility into finances',
            'Streamline vendor relationships',
            'Improve cash flow management',
            'Simplify tax preparation',
        ],
        process: [
            { step: 'Assessment', description: 'We analyze your current financial structure and identify opportunities for improvement.' },
            { step: 'Setup', description: 'We configure systems, establish workflows, and integrate with your existing accounts.' },
            { step: 'Transition', description: 'We carefully migrate historical data and begin managing day-to-day operations.' },
            { step: 'Ongoing Management', description: 'We handle all accounting functions with regular reporting and communication.' },
        ],
        category: 'family-office',
        icon: 'Calculator',
    },
    {
        slug: 'vendor-selection',
        title: 'Vendor Selection',
        shortDescription: 'Rigorous vetting and management of service providers.',
        fullDescription: [
            'Finding trustworthy service providers is critical for high-net-worth families. Our vendor selection service ensures you work only with vetted, qualified professionals who meet our rigorous standards for quality, reliability, and discretion.',
            'We conduct thorough due diligence on all potential vendors, including comprehensive background checks, reference verification, financial stability assessments, and insurance verification. Our process is designed to protect your family from risk while ensuring you receive exceptional service.',
            'Our ongoing vendor management ensures continued performance and accountability. We monitor service quality, manage contracts, and address any issues that arise, serving as your advocate in all vendor relationships.',
            'From household staff to investment managers, from attorneys to art advisors, we help you build a trusted network of service providers who understand the unique needs of affluent families.',
        ],
        features: [
            'Comprehensive vendor due diligence and background checks',
            'Reference verification and reputation assessment',
            'Financial stability and insurance verification',
            'Contract negotiation and review support',
            'Performance monitoring and quality assurance',
            'Vendor relationship management',
            'Cost optimization and benchmarking analysis',
            'Service level agreement development and oversight',
            'Vendor consolidation strategies',
            'Emergency vendor replacement protocols',
            'Confidentiality agreement management',
            'Vendor payment and invoice processing',
        ],
        benefits: [
            'Reduce risk of fraud or poor service',
            'Save time on vendor research',
            'Negotiate better terms and pricing',
            'Ensure consistent service quality',
            'Maintain confidentiality and privacy',
            'Build a trusted service provider network',
        ],
        process: [
            { step: 'Needs Analysis', description: 'We understand your specific requirements and preferences for each service category.' },
            { step: 'Candidate Sourcing', description: 'We identify and pre-screen potential vendors from our network and beyond.' },
            { step: 'Due Diligence', description: 'We conduct comprehensive vetting including background checks and reference calls.' },
            { step: 'Selection & Onboarding', description: 'We facilitate introductions, negotiate terms, and manage the onboarding process.' },
        ],
        category: 'family-office',
        icon: 'Users',
    },
    {
        slug: 'technology-implementation',
        title: 'Technology Implementation',
        shortDescription: 'Modern infrastructure setup and integration.',
        fullDescription: [
            'We help families implement modern technology solutions that enhance efficiency, security, and communication across all aspects of their lives. Our technology team brings deep expertise in both consumer and enterprise solutions.',
            'From selecting the right software platforms to ensuring seamless integration, our technology team guides you through every step of the implementation process. We evaluate options, manage vendors, and ensure successful deployment.',
            'We prioritize security and usability, ensuring your technology infrastructure supports your family\'s needs while protecting sensitive information. Every solution we recommend undergoes rigorous security review.',
            'Our ongoing support ensures your technology continues to serve you well, with regular updates, training, and optimization to keep pace with evolving needs and threats.',
        ],
        features: [
            'Technology needs assessment and roadmap development',
            'Software selection and procurement',
            'System integration and data migration',
            'Cloud infrastructure setup and management',
            'Cybersecurity implementation and monitoring',
            'User training and adoption support',
            'Ongoing technical support and maintenance',
            'Smart home and property technology',
            'Communication and collaboration tools',
            'Document management systems',
            'Password and identity management',
            'Backup and disaster recovery planning',
        ],
        benefits: [
            'Streamline family operations',
            'Enhance security and privacy',
            'Improve communication and collaboration',
            'Reduce technology frustration',
            'Future-proof your infrastructure',
            'Access expert support when needed',
        ],
        process: [
            { step: 'Discovery', description: 'We assess your current technology landscape and identify pain points and opportunities.' },
            { step: 'Strategy', description: 'We develop a comprehensive technology roadmap aligned with your goals.' },
            { step: 'Implementation', description: 'We deploy solutions with minimal disruption, including data migration and integration.' },
            { step: 'Training & Support', description: 'We ensure all users are comfortable and provide ongoing support.' },
        ],
        category: 'family-office',
        icon: 'Cpu',
    },
    {
        slug: 'custom-reporting',
        title: 'Custom Reporting',
        shortDescription: 'Tailored financial and operational reporting.',
        fullDescription: [
            'Our custom reporting services provide the insights you need to make informed decisions about your wealth. We transform complex financial data into clear, actionable information tailored to your specific needs.',
            'We create tailored reports that consolidate information from multiple sources—investments, real estate, businesses, trusts—giving you a comprehensive view of your financial position in one place.',
            'Reports are designed to meet your specific needs, whether for family meetings, tax planning, investment review, or estate planning. We work with you to determine the right metrics, format, and frequency.',
            'Our reporting platform provides both scheduled reports and on-demand access, ensuring you always have the information you need when you need it.',
        ],
        features: [
            'Consolidated financial statements across all entities',
            'Investment performance reporting and benchmarking',
            'Net worth tracking and trend analysis',
            'Budget vs. actual variance analysis',
            'Tax planning and projection reports',
            'Family meeting presentation materials',
            'Real-time dashboards and mobile access',
            'Custom KPI tracking and alerts',
            'Estate and trust reporting',
            'Philanthropic giving analysis',
            'Real estate portfolio reporting',
            'Alternative investment tracking',
        ],
        benefits: [
            'Gain complete visibility into your wealth',
            'Make better-informed decisions',
            'Simplify family communication',
            'Streamline advisor coordination',
            'Track progress toward goals',
            'Identify opportunities and risks',
        ],
        process: [
            { step: 'Requirements Gathering', description: 'We understand your reporting needs, preferences, and decision-making processes.' },
            { step: 'Data Integration', description: 'We connect to all relevant data sources and establish automated feeds.' },
            { step: 'Report Design', description: 'We create custom report templates tailored to your specifications.' },
            { step: 'Delivery & Refinement', description: 'We deliver reports on your schedule and continuously refine based on feedback.' },
        ],
        category: 'family-office',
        icon: 'FileText',
    },
    {
        slug: 'digital-identity-protection',
        title: 'Digital Identity Protection',
        shortDescription: 'Comprehensive cybersecurity for family members.',
        fullDescription: [
            'Protecting your family\'s digital identity is essential in today\'s connected world. High-net-worth individuals and their families face elevated risks from cybercriminals, making proactive protection critical.',
            'Our digital identity protection services safeguard your online presence through continuous monitoring, threat detection, and rapid response. We watch for signs of identity theft, account compromise, and reputation threats.',
            'We monitor for threats across the surface web, deep web, and dark web, manage your digital footprint, and implement security measures to protect against identity theft and cyber attacks.',
            'Our proactive approach ensures your family\'s privacy and security across all digital platforms, from social media to financial accounts to smart home devices.',
        ],
        features: [
            'Dark web monitoring for personal information',
            'Identity theft protection and recovery services',
            'Social media security and privacy optimization',
            'Digital footprint management and reduction',
            'Secure communication setup (encrypted email, messaging)',
            'Password management and security',
            'Device security assessment and hardening',
            'Family security awareness training',
            'Phishing and social engineering protection',
            'Account takeover prevention',
            'Credit monitoring and fraud alerts',
            'Incident response and recovery support',
        ],
        benefits: [
            'Protect against identity theft',
            'Maintain family privacy',
            'Reduce digital exposure',
            'Respond quickly to threats',
            'Educate family members on security',
            'Peace of mind in the digital age',
        ],
        process: [
            { step: 'Security Assessment', description: 'We evaluate your current digital exposure and identify vulnerabilities.' },
            { step: 'Protection Setup', description: 'We implement monitoring, security tools, and protective measures.' },
            { step: 'Training', description: 'We educate family members on security best practices and threat awareness.' },
            { step: 'Ongoing Monitoring', description: 'We continuously monitor for threats and respond to incidents.' },
        ],
        category: 'family-office',
        icon: 'ShieldCheck',
    },
]

export const cybersecurityServices: ServiceItem[] = [
    {
        slug: 'rapid-diagnostic',
        title: 'Rapid Diagnostic',
        shortDescription: 'SEC cybersecurity compliance assessment through a two-session executive diagnostic process.',
        fullDescription: [
            'Our Rapid Diagnostic service provides a quick yet comprehensive assessment of your cybersecurity posture, designed specifically for investment advisors and family offices subject to SEC oversight.',
            'Through two focused executive sessions, we identify vulnerabilities, assess compliance with SEC cybersecurity requirements, and develop a prioritized remediation roadmap that addresses the most critical risks first.',
            'This service is ideal for organizations seeking to understand their current security state, prepare for regulatory examinations, or plan strategic security improvements.',
            'Our experienced team brings deep knowledge of both cybersecurity best practices and regulatory requirements, ensuring our recommendations are practical and compliant.',
        ],
        features: [
            'SEC cybersecurity compliance assessment',
            'Two executive diagnostic sessions',
            'Vulnerability identification and prioritization',
            'Risk assessment and scoring',
            'Remediation roadmap development',
            'Compliance gap analysis',
            'Executive summary report',
            'Board-ready presentation materials',
            'Action plan with timelines',
            'Resource and budget estimates',
            'Regulatory examination preparation',
            'Follow-up consultation included',
        ],
        benefits: [
            'Quickly understand your security posture',
            'Identify critical vulnerabilities',
            'Prepare for SEC examinations',
            'Prioritize security investments',
            'Get actionable recommendations',
            'Minimal time commitment required',
        ],
        process: [
            { step: 'Pre-Session Preparation', description: 'We gather documentation and prepare targeted questions for efficient sessions.' },
            { step: 'Session 1: Discovery', description: 'We conduct a comprehensive review of your security policies, procedures, and infrastructure.' },
            { step: 'Analysis', description: 'Our team analyzes findings and develops recommendations.' },
            { step: 'Session 2: Findings & Roadmap', description: 'We present findings and collaborate on a prioritized action plan.' },
        ],
        category: 'cybersecurity',
        icon: 'Search',
    },
    {
        slug: 'basic-cybersecurity',
        title: 'Basic Cybersecurity Package',
        shortDescription: 'Foundation-level protection with CIS Controls Framework implementation.',
        fullDescription: [
            'Our Basic Cybersecurity Package provides essential protection for organizations beginning their security journey or those with limited security resources.',
            'Built on the CIS Controls Framework—a proven set of security best practices—this package establishes fundamental security measures that address the most common attack vectors.',
            '24/7 monitoring ensures threats are detected and addressed promptly, with our security operations center watching your environment around the clock.',
            'This package is designed to provide meaningful security improvement quickly and cost-effectively, creating a foundation for more advanced security measures as your needs evolve.',
        ],
        features: [
            'CIS Controls Framework implementation',
            'Endpoint detection and response (EDR)',
            '24/7 security monitoring and alerting',
            'Firewall monitoring and management',
            'Basic threat detection and response',
            'Security alerts and incident notifications',
            'Monthly security status reports',
            'Email security and anti-phishing',
            'Vulnerability scanning (quarterly)',
            'Security policy templates',
            'Employee security awareness basics',
            'Dedicated security advisor',
        ],
        benefits: [
            'Establish security fundamentals',
            'Detect threats quickly',
            'Meet basic compliance requirements',
            'Reduce attack surface',
            'Get expert security guidance',
            'Cost-effective protection',
        ],
        process: [
            { step: 'Assessment', description: 'We evaluate your current security state and identify gaps.' },
            { step: 'Implementation', description: 'We deploy monitoring tools and security controls.' },
            { step: 'Configuration', description: 'We tune systems to your environment and establish baselines.' },
            { step: 'Monitoring', description: 'We begin 24/7 monitoring with regular reporting and communication.' },
        ],
        category: 'cybersecurity',
        icon: 'Shield',
    },
    {
        slug: 'advanced-cybersecurity',
        title: 'Advanced Cybersecurity Package',
        shortDescription: 'Enhanced protection with advanced analytics and virtual CISO services.',
        fullDescription: [
            'The Advanced Cybersecurity Package builds on our basic offering with sophisticated analytics, proactive threat hunting, and strategic security leadership.',
            'Virtual CISO services provide executive-level security leadership without the cost of a full-time hire. Your vCISO serves as a trusted advisor, helping you navigate security decisions and communicate with stakeholders.',
            'Advanced identity and access management ensures only authorized users can access sensitive systems, with multi-factor authentication and privileged access controls.',
            'This package is ideal for organizations with regulatory requirements, sensitive data, or elevated threat profiles who need comprehensive security management.',
        ],
        features: [
            'All Basic Package services included',
            'Advanced security analytics and SIEM',
            'Identity & access management (IAM)',
            'Multi-factor authentication deployment',
            'Incident response planning and playbooks',
            'Virtual CISO services (monthly advisory)',
            'Security awareness training program',
            'Vulnerability assessments (monthly)',
            'Compliance management and reporting',
            'Third-party risk assessments',
            'Security architecture review',
            'Tabletop exercises (annual)',
        ],
        benefits: [
            'Strategic security leadership',
            'Advanced threat detection',
            'Stronger access controls',
            'Comprehensive compliance support',
            'Proactive risk management',
            'Board-level security reporting',
        ],
        process: [
            { step: 'Strategic Planning', description: 'Your vCISO develops a security strategy aligned with business objectives.' },
            { step: 'Enhanced Deployment', description: 'We implement advanced controls and monitoring capabilities.' },
            { step: 'Training & Awareness', description: 'We roll out security awareness programs for all staff.' },
            { step: 'Ongoing Advisory', description: 'Your vCISO provides continuous guidance and quarterly reviews.' },
        ],
        category: 'cybersecurity',
        icon: 'ShieldAlert',
    },
    {
        slug: 'comprehensive-cybersecurity',
        title: 'Comprehensive Cybersecurity Package',
        shortDescription: 'Complete enterprise-grade security with full governance and reporting.',
        fullDescription: [
            'Our Comprehensive Cybersecurity Package delivers enterprise-grade protection for organizations with the highest security requirements and most sensitive data.',
            'This package includes proactive threat hunting by experienced analysts who actively search for signs of compromise, penetration testing to identify vulnerabilities before attackers do, and full incident response management.',
            'Complete governance and reporting ensure board-level visibility into security posture, with metrics and dashboards that communicate risk in business terms.',
            'Designed for organizations subject to stringent regulatory requirements or those managing highly sensitive information, this package provides the most complete security coverage available.',
        ],
        features: [
            'All Advanced Package services included',
            'Privileged identity management (PIM)',
            'Penetration testing (bi-annual)',
            'Proactive threat hunting',
            'Full incident response management',
            'Complete governance framework',
            'Board-level reporting and dashboards',
            'Regulatory compliance management',
            'Security architecture design',
            'Data loss prevention (DLP)',
            'Cloud security posture management',
            'Red team exercises (annual)',
            '24/7 incident response hotline',
            'Cyber insurance coordination',
        ],
        benefits: [
            'Enterprise-grade protection',
            'Proactive threat detection',
            'Complete compliance coverage',
            'Board-ready reporting',
            'Rapid incident response',
            'Continuous security improvement',
        ],
        process: [
            { step: 'Comprehensive Assessment', description: 'We conduct a thorough evaluation of your security program and risks.' },
            { step: 'Governance Framework', description: 'We establish policies, procedures, and reporting structures.' },
            { step: 'Full Deployment', description: 'We implement all security controls and monitoring capabilities.' },
            { step: 'Continuous Improvement', description: 'We provide ongoing management, testing, and optimization.' },
        ],
        category: 'cybersecurity',
        icon: 'Crown',
    },
]

export const allServices = [...familyOfficeServices, ...cybersecurityServices]

export function getServiceBySlug(slug: string): ServiceItem | undefined {
    return allServices.find(service => service.slug === slug)
}
